batch_size: 16384
clamp: false
clamp_value: 0.5
epochs: 3000
inner_dim: 1024
latent_size: 512
loss_multiplier: 1
lr_latent: 0.0001
lr_model: 0.0001
lr_multiplier: 0.9
lr_scheduler: true
num_layers: 8
patience: 20
pretrain_optim_latent: ''
pretrain_optim_model: ''
pretrain_weights: ''
pretrained: false
seed: 36
sigma_regulariser: 0.001
skip_connections: true
